# Generated by Django 5.1.5 on 2025-02-04 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retriver',
            options={'verbose_name': 'Retriver'},
        ),
    ]
