# Generated by Django 5.1.5 on 2025-02-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_rename_retriver_userdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdata',
            options={'verbose_name': 'User Data'},
        ),
        migrations.AddField(
            model_name='userdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='currentDate',
            field=models.DateField(auto_now=True),
        ),
    ]
