# Generated by Django 5.1.5 on 2025-02-05 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_alter_userdata_options_userdata_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='updated_at',
            new_name='current_datetime',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='gitUrl',
            new_name='github_url',
        ),
    ]
